// packages/core/src/components/filter/filter.tsx
import { Component, Prop, h, Event, EventEmitter } from '@stencil/core';

/**
 * @slot - 'admiralty-filter-group' components can be placed inside of this element to render groups of filter controls. You can also place any elements you wish
 */
@Component({
  tag: 'admiralty-filter',
  styleUrl: 'filter.scss',
  scoped: true,
})
export class FilterComponent {
  /**
   * The title of the filter
   */
  @Prop() filterTitle = 'Filter';

  /**
   * Event that is emitted when the filters are cleared
   */
  @Event() filterCleared: EventEmitter<void>;

  /**
   * Event that is emitted when the filters are applied
   */
  @Event() filterApplied: EventEmitter<void>;

  private onFilterCleared = (ev: Event) => {
    ev.preventDefault();
    this.filterCleared.emit();
  };

  private onFilterApplied = (ev: Event) => {
    ev.preventDefault();
    this.filterApplied.emit();
  };

  render() {
    return (
      <div class="filter-container">
        <div class="filter-heading">
          <div class="filter-title">{this.filterTitle}</div>
          <div class="button-wrapper">
            <button type="reset" class="text-link" aria-label="Clear selected filters" onClick={this.onFilterCleared}>
              Clear
            </button>
          </div>
        </div>
        <div>
          <slot></slot>
        </div>
        <div>
          <admiralty-button onClick={this.onFilterApplied}>Apply filters</admiralty-button>
        </div>
      </div>
    );
  }
}

// components/filter/filter.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FilterGroup, FilterItem } from './filter.types';

@Component({
  selector: 'ukho-filter',
  templateUrl: './filter.component.html',
  styleUrls: ['./filter.component.scss'],
})
export class FilterComponent {
  @Input() groups: FilterGroup[];
  @Input() heading: string = 'Filters';

  /**
   * An event that is emitted when the Apply Filters button is pressed.
   *
   * The event will contain an array of filter groups.
   */
  @Output() filtersChange = new EventEmitter<FilterGroup[]>();

  onExpansionChange(filterGroup: FilterGroup) {
    this.groups = this.groups.map((group: FilterGroup) => {
      if (group.title !== filterGroup.title) {
        return group;
      }
      const { expanded, ...rest } = group;
      return { ...rest, ...(!filterGroup.expanded && { expanded: true }) };
    });
  }

  onCheckboxChange(filterGroup: FilterGroup, filterItem: FilterItem) {
    this.groups = this.groups.map((group: FilterGroup) => {
      if (group.title !== filterGroup.title) {
        return group;
      }
      const items = group.items.map((item: FilterItem) => {
        if (item.title !== filterItem.title) {
          return item;
        }
        const { selected, ...rest } = item;
        return { ...rest, ...(!filterItem.selected && { selected: true }) };
      });
      return { ...group, items };
    });
  }

  onClear(): void {
    this.groups = this.groups.map((group: FilterGroup) => {
      const items = group.items.map((item: FilterItem) => {
        const { selected, ...rest } = item;
        return rest;
      });
      return { ...group, items };
    });
  }

  onApply(): void {
    this.filtersChange.emit(this.groups);
  }
}

<section class="filters">
  <header class="heading">
    <h2>{{heading}}</h2>
    <button type="reset" class="text-link" (click)="onClear()">Clear</button>
  </header>
  <ukho-expansion *ngFor="let group of groups" (change)="onExpansionChange(group)" [hideBorder]="true" [heading]="group.title" [initialExpanded]="group.expanded">
    <nav class="filter-items" [attr.aria-label]="group.title">
      <ukho-checkbox *ngFor="let item of group.items" (change)="onCheckboxChange(group, item)" [checkboxRight]="true" [checked]="item.selected" [justify]="true">{{item.title}}</ukho-checkbox>
    </nav>
  </ukho-expansion>
  <ukho-button (click)="onApply()">Apply filters</ukho-button>
</section>
