// components/paginator/paginator.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'ukho-paginator',
  templateUrl: './paginator.component.html',
  styleUrls: ['./paginator.component.scss'],
})
export class PaginatorComponent {
  /**
   * The total number of pages. Defaults to 1.
   */
  @Input() pages = 1;

  /**
   * The current page. Defaults to 1.
   */
  @Input() currentPage = 1;

  /**
   * The label to display.
   */
  @Input() set label(label: string) {
    this.setLabel(label);
  }

  @Output() pageChange = new EventEmitter<number>();

  _label = '';
  readonly maxLength = 7;

  public setLabel(label: string) {
    if (label == null || label.length === 0) {
      return;
    }
    this._label = label;
  }

  public pageChanged(page: number) {
    this.pageChange.emit(page);
  }

  prev() {
    if (this.currentPage > 1) {
      this.pageChanged(this.currentPage - 1);
    }
  }

  next() {
    if (this.currentPage < this.pages) {
      this.pageChanged(this.currentPage + 1);
    }
  }
}

<nav aria-label="pagination" class="standard">
  <p aria-live="polite">{{ _label }}</p>
  <a
    role="button"
    class="pagination-anchor"
    tabindex="0"
    attr.aria-disabled="{{ this.currentPage === 1 }}"
    [ngClass]="{ disabled: this.currentPage === 1 }"
    (click)="prev()"
    (keydown.enter)="prev()"
    (keydown.space)="prev()"
    aria-label="Previous Page"
  >
    <i class="fas fa-chevron-left"></i>
  </a>
  <a
    role="button"
    class="pagination-anchor"
    tabindex="0"
    attr.aria-disabled="{{ this.currentPage === this.pages }}"
    [ngClass]="{ disabled: this.currentPage === this.pages }"
    (click)="next()"
    (keydown.enter)="next()"
    (keydown.space)="next()"
    aria-label="Next Page"
  >
    <i class="fas fa-chevron-right"></i>
  </a>
</nav>

// packages/core/src/components/paginator/paginator.tsx
import { Component, Prop, h, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'admiralty-paginator',
  styleUrl: 'paginator.scss',
  scoped: true,
})
export class PaginatorComponent {
  /**
   * The total number of pages. Defaults to 1.
   */
  @Prop() pages = 1;
  /**
   * The current page. Defaults to 1.
   */
  @Prop() currentPage = 1;
  /**
   * The label to display.
   */
  @Prop() label: string = '';
  /**
   * Dispatched when the previous or next button is pressed. The event detail contains
   * the requested page number.
   */
  @Event() pageChange: EventEmitter<number>;

  readonly maxLength = 7;

  public pageChanged(page: number) {
    this.pageChange.emit(page);
  }

  onKeydown(event: KeyboardEvent, navFn: Function) {
    if (event.key === 'Enter' || event.key === 'Enter') {
      navFn();
    }
  }

  prev() {
    if (this.currentPage > 1) {
      this.pageChanged(this.currentPage - 1);
    }
  }

  next() {
    if (this.currentPage < this.pages) {
      this.pageChanged(this.currentPage + 1);
    }
  }

  render() {
    return (
      <nav aria-label="pagination" class="standard">
        <p aria-live="polite">{this.label}</p>
        <admiralty-button
          variant="icon"
          icon="arrow-back-ios-new-rounded"
          disabled={this.currentPage === 1}
          aria-disabled={this.currentPage === 1}
          onClick={this.prev.bind(this)}
          onKeyDown={e => this.onKeydown(e, this.prev.bind(this))}
          aria-label="Previous Page"
        ></admiralty-button>
        <admiralty-button
          variant="icon"
          icon="arrow-forward-ios-rounded"
          disabled={this.currentPage === this.pages}
          aria-disabled={this.currentPage === this.pages}
          onClick={this.next.bind(this)}
          onKeyDown={e => this.onKeydown(e, this.next.bind(this))}
          aria-label="Next Page"
        ></admiralty-button>
      </nav>
    );
  }
}
