// packages/core/src/components/phase-banner/phase-banner.tsx
import { Component, Prop, h } from '@stencil/core';

@Component({
  tag: 'admiralty-phase-banner',
  styleUrl: 'phase-banner.scss',
  scoped: true,
})
export class PhaseBannerComponent {
  /**
   * The phase for the phase banner
   */
  @Prop() phase: 'alpha' | 'beta' = 'alpha';

  /**
   * A link to where the end user can provide feedback
   */
  @Prop() link: string;

  render() {
    return (
      <div class="phase-banner">
        <strong>{this.phase}</strong>
        <span>
          This service is in {this.phase} phase - please provide{' '}
          <a href={this.link} target="_blank">
            feedback
          </a>{' '}
          to help us improve it
        </span>
      </div>
    );
  }
}

// projects/components/src/lib/phase-banner/phase-banner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'ukho-phase-banner',
  templateUrl: './phase-banner.component.html',
  styleUrls: ['./phase-banner.component.scss']
})
export class PhaseBannerComponent {
  @Input() link: string;
  @Input() phase: 'alpha' | 'beta' = 'alpha';
}

<strong>{{ phase }}</strong>
This service is in {{ phase }} phase - please provide <a [href]="link" target="_blank">feedback</a> to help us improve it
