// components/button/button.component.ts
import { ChangeDetectionStrategy, Component, Input, OnInit, SimpleChanges, ViewEncapsulation } from '@angular/core';
import { ButtonVariant } from './button.types';

@Component({
  selector: 'ukho-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ButtonComponent implements OnInit {
  /**
   * The type of button to render. Valid values are `primary`, `secondary`, `warning`, `text` and `icon`.
   * Default value is `primary`.
   */
  @Input() variant: ButtonVariant;
  /**
   * Deprecated. Whether the button should be rendered as a secondary type of button. Will take
   * precedent over `variant`.
   *
   * @deprecated
   * - Use the `variant` input property instead.
   */
  @Input() secondary = false;
  /**
   * When passed Font Awesome class names, then an icon will be rendered.
   */
  @Input() icon: string;
  /**
   * Determines whether the button is disabled. A button in disabled state will not fire click output events.
   */
  @Input() disabled = false;
  /**
   * The default behavior of the button. Valid values are `button`, `submit` and `reset`.
   * Default value is `submit`.
   */
  @Input() type: 'button' | 'submit' | 'reset' = 'submit';

  ngOnInit(): void {
    if (!this.variant) {
      this.variant = ButtonVariant.Primary;
    }
    if (this.secondary) {
      this.variant = ButtonVariant.Secondary;
    }
  }
}

<button [disabled]="disabled" class="{{ secondary ? 'secondary' : '' }}">
  <ng-content></ng-content>
  <i *ngIf="icon" class="{{ icon }}"></i>
</button>

// packages/core/src/components/button/button.tsx
import { Component, Prop, h } from '@stencil/core';
import { ButtonVariant } from './button.types';
import { IconName } from '@fortawesome/fontawesome-svg-core';

@Component({
  tag: 'admiralty-button',
  styleUrl: 'button.scss',
  scoped: true,
})
export class ButtonComponent {
  /**
   * The type of button to render. Valid values are `primary`, `secondary`, `warning`, `text` and `icon`.
   * Default value is `primary`.
   */
  @Prop() variant: ButtonVariant;
  /**
   * When passed Font Awesome Icon name, then an icon will be rendered.
   */
  @Prop() icon: IconName;
  /**
   * Determines whether the button is disabled. A button in disabled state will not fire click output events.
   */
  @Prop() disabled = false;
  /**
   * The default behavior of the button. Valid values are `button`, `submit` and `reset`.
   * Default value is `submit`.
   */
  @Prop() type: 'button' | 'submit' | 'reset' = 'submit';

  render() {
    return (
      <button type={this.type} disabled={this.disabled ? true : null} class={this.variant || ButtonVariant.Primary}>
        <slot></slot>
        {this.icon ? <admiralty-icon icon-name={this.icon}></admiralty-icon> : undefined}
      </button>
    );
  }
}
