// angular/components/typeahead/typeahead.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  QueryList,
  ViewChild,
  ViewChildren,
} from '@angular/core';
import { FormControl } from '@angular/forms';
import { Observable, of, Subject, Subscription } from 'rxjs';
import { debounceTime, filter, mergeMap } from 'rxjs/operators';

enum Keys {
  UP_ARROW = 'ArrowUp',
  DOWN_ARROW = 'ArrowDown',
  ENTER = 'Enter',
}

let nextId = 0;

@Component({
  selector: 'ukho-typeahead',
  templateUrl: './typeahead.component.html',
  styleUrls: ['./typeahead.component.scss'],
})
export class TypeaheadComponent implements OnInit, OnDestroy {
  /**
   * Function that will be executed to filter the results shown in the typeahead
   */
  @Input() filterFn: (filterTerm: string) => string[] | Observable<string[]>;
  /**
   * Model that will track the contents of the input field
   *
   * @deprecated
   * - Use the `value` input property instead to set the `value`
   * - Use the `valueChanged` output or `value` input property to retrieve the current value
   */
  @Input() FormControl: FormControl = new FormControl();
  /**
   * The value of the textinput
   */
  @Input()
  get value(): string {
    return this.FormControl.value;
  }
  set value(value: string) {
    if (typeof value === 'undefined' || value === null || value.length < 1) {
      return;
    }
    this.FormControl.setValue(value);
  }
  /**
   * The text content of the label for the input box
   */
  @Input() label: string;
  /**
   * Optional property to show results when input box is initally focused
   */
  @Input() showResultsOnInitialFocus = false;

  /**
   * Event that is fired whenever the value of the typeahead changes
   * e.g. selection from the dropdown or manually typed entry
   */
  @Output() valueChanged: EventEmitter<string> = new EventEmitter<string>();

  /**
   * A reference to the typeahead list wrapper
   */
  @ViewChild('typeaheadListContainer') listContainer: ElementRef;

  /**
   * A reference to the typeahead list items
   */
  @ViewChildren('typeaheadListItems') listItems: QueryList<ElementRef>;

  filterResult: string[] = new Array<string>();
  selectedItemIndex = -1;
  isFocused = false;

  isSilenced = false;
  isDebounced = false;
  isAlternateStatusSection = false;
  statusText: string;

  id = `ukho-typeahead-${++nextId}`;
  hintId = `${this.id}-assistive-hint`;
  listId = `${this.id}-list`;

  private originalSearch = '';
  private hasBeenFocusedAtLeastOnce = false;

  private subscription: Subscription;
  private searchTextChanged$ = new Subject<string>();
  private selectedOption: string;

  /**
   * Optional function that will be executed when the user selects an item from the typeahead
   */
  @Input() selectionAction: (selectedItemText) => unknown = () => {};

  ngOnInit(): void {
    this.subscription = this.searchTextChanged$
      .pipe(
        debounceTime(1400),
        filter(() => !this.isSilenced),
        mergeMap(this.getStatusText),
      )
      .subscribe(this.setStatusText);
  }

  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }

  focusIn() {
    if (this.showResultsOnInitialFocus && !this.hasBeenFocusedAtLeastOnce) {
      this.performFilter('');
      this.hasBeenFocusedAtLeastOnce = true;
    }

    this.isFocused = true;
    this.isSilenced = false;
    // Ensure the status text updates
    this.searchTextChanged$.next();
  }

  focusOut() {
    this.isFocused = false;
    this.statusText = null;
    this.isSilenced = true;
  }

  textChanged = (value: string): void => {
    this.originalSearch = value;
    this.selectedOption = null;
    this.performFilter(value);
    this.isDebounced = false;
    this.isSilenced = false;
    this.searchTextChanged$.next();
    this.valueChanged.emit(value);
  };

  keyPressed = (event: KeyboardEvent): void => {
    if (event.key === Keys.UP_ARROW || event.key === Keys.DOWN_ARROW) {
      this.navigateSuggestions(event.key);
      this.updateScroll();
    } else if (event.key !== Keys.ENTER) {
      this.textChanged(this.FormControl.value);
    }
  };

  itemSelected = (value: string): void => {
    this.FormControl.setValue(value);
    this.textChanged(value);
    this.selectedOption = value;
    this.searchTextChanged$.next();
    this.filterResult = new Array<string>();
    this.selectionAction(value);
  };

  performFilter(value: string) {
    const filterResult = this.filterFn(value);
    if (filterResult instanceof Array) {
      this.filterResult = filterResult;
    } else if (filterResult instanceof Observable) {
      filterResult.subscribe((filterValue) => {
        this.filterResult = filterValue;
      });
    }
    this.selectedItemIndex = -1;
  }

  selectCurrentItem(): void {
    if (this.selectedItemIndex >= 0) {
      const selectedItemText = this.filterResult[this.selectedItemIndex];
      this.itemSelected(selectedItemText);
    }
  }

  itemHovered(index: number): void {
    this.selectedItemIndex = index;
  }

  setStatusText = (text: string) => {
    // Switching between status sections ensures that screen readers will read out
    // the status message even if the result count remains the same
    this.isAlternateStatusSection = !this.isAlternateStatusSection;
    this.statusText = text;
    this.isDebounced = true;
  };

  /**
   * Status text to be read out by screen readers
   */
  getStatusText = (): Observable<string> => {
    const results = this.filterResult.length;
    if (!results) {
      return of('No search results');
    }
    const words = {
      result: results === 1 ? 'result' : 'results',
      is: results === 1 ? 'is' : 'are',
    };

    const contentSelectedOption = this.selectedOption
      ? `${this.selectedOption} ${this.selectedItemIndex + 1} of ${results} is highlighted.`
      : '';

    return of(`${results} ${words.result} ${words.is} available. ${contentSelectedOption}`);
  };

  /**
   * Check if the selected option is in view, and scroll if not
   */
  updateScroll() {
    const container = this.listContainer?.nativeElement;
    const selectedOption = this.listItems
      .toArray()
      .find((item) => item.nativeElement.ariaPosInSet === `${this.selectedItemIndex + 1}`)?.nativeElement;
    if (container && selectedOption && container.scrollHeight + container.clientHeight) {
      const scrollBottom = container.clientHeight + container.scrollTop;
      const elementBottom = selectedOption.offsetTop + selectedOption.offsetHeight;
      if (elementBottom > scrollBottom) {
        container.scrollTop = elementBottom - container.clientHeight;
      } else if (selectedOption.offsetTop < container.scrollTop) {
        container.scrollTop = selectedOption.offsetTop;
      }
    }
  }

  private navigateSuggestions(key: Keys) {
    if (key === Keys.UP_ARROW) {
      this.selectedItemIndex--;
      if (this.selectedItemIndex === -2) {
        this.selectedItemIndex = this.filterResult.length - 1;
      }
    }
    if (key === Keys.DOWN_ARROW) {
      this.selectedItemIndex++;
      if (this.selectedItemIndex > this.filterResult.length - 1) {
        this.selectedItemIndex = -1;
      }
    }
    if (this.selectedItemIndex === -1) {
      this.FormControl.setValue(this.originalSearch);
    } else {
      const value = this.filterResult[this.selectedItemIndex];
      this.FormControl.setValue(value);
      this.selectedOption = value;
      this.searchTextChanged$.next();
    }
  }
}

<div class="visually-hidden">
  <div class="results-status-a" role="status" aria-atomic="true" aria-live="polite">
    {{ !isSilenced && isAlternateStatusSection ? statusText : "" }}
  </div>
  <div class="results-status-b" role="status" aria-atomic="true" aria-live="polite">
    {{ !isSilenced && !isAlternateStatusSection ? statusText : "" }}
  </div>
</div>
<ukho-textinput
  type="text"
  [label]="label"
  [formControl]="FormControl"
  (keyup)="keyPressed($event)"
  (keyup.enter)="selectCurrentItem()"
  (keydown.tab)="selectCurrentItem()"
  autocomplete="list"
  class="filterTextInput"
  (focusin)="focusIn()"
  (focusout)="focusOut()"
  [ariaExpanded]="isFocused && filterResult.length > 0"
  [ariaOwns]="listId"
  ariaRole="combobox"
  [ariaDescribedBy]="isFocused && filterResult.length > 0 ? null : hintId"
></ukho-textinput>
<span id="{{hintId}}" class="visually-hidden">
  When autocomplete results are available use up and down arrows to review and enter to select. Touch device users,
  explore by touch or with swipe gestures.
</span>
<div #typeaheadListContainer class="typeahead-list-container" *ngIf="filterResult.length > 0">
  <ul class="typeahead-list" id="{{listId}}" role="listbox">
    <li
      #typeaheadListItems
      *ngFor="let item of filterResult; let i = index"
      (mousedown)="itemSelected(item)"
      (mouseover)="itemHovered(i)"
      [attr.aria-selected]="i == selectedItemIndex"
      [attr.selected]="i == selectedItemIndex"
      [ngClass]="{ highlighted: i == selectedItemIndex }"
      role="option"
      tabindex="-1"
      [attr.aria-posinset]="i + 1"
      [attr.aria-setsize]="filterResult.length"
    >
      {{ item }}
    </li>
  </ul>
</div>

// packages/core/src/components/type-ahead/type-ahead.tsx
import { Component, EventEmitter, Host, Prop, Event, h, State, Element } from '@stencil/core';
import { Keys } from '../Keys';

@Component({
  tag: 'admiralty-type-ahead',
  styleUrl: 'type-ahead.scss',
  scoped: true,
})
export class TypeAheadComponent {
  private _id = `admiralty-typeahead-${++id}`;

  hintId = `${this._id}-assistive-hint`;
  listId = `${this._id}-list`;

  @Element() el: HTMLElement;

  listContainer!: HTMLDivElement;
  inputControl!: HTMLAdmiraltyInputElement;

  @State() filterResult: string[] = new Array<string>();

  filterList: Array<string> = [];

  selectedItemIndex = -1;
  isFocused = false;

  isSilenced = false;
  isAlternateStatusSection = false;
  statusText: string;

  private originalSearch = '';
  private hasBeenFocusedAtLeastOnce = false;

  private get inputValue() {
    return this.inputControl.value.toString();
  }

  private set inputValue(value: string) {
    this.inputControl.value = value;
  }

  /**
   * The value of the textinput
   */
  @Prop() value: string;

  /**
   * The text content of the label for the input box
   */
  @Prop() label: string;

  /**
   * The placeholder text for the input field
   */
  @Prop() placeholder: string;

  /**
   * Optional property to show results when input box is initally focused
   */
  @Prop() resultsOnInitFocus: boolean = false;

  /**
   * Optional function that will be executed when the user selects an item from the typeahead
   */
  @Event() selectionChanged: EventEmitter<string>;

  /**
   * Event that is fired whenever the value of the typeahead changes
   * e.g. selection from the dropdown or manually typed entry
   */
  @Event() valueChanged: EventEmitter<string>;

  connectedCallback() {
    const slotItems = this.el.querySelectorAll('admiralty-type-ahead-item');
    slotItems.forEach(el => {
      this.filterList.push(el.getAttribute('value'));
    });
  }

  componentDidLoad() {
    if (this.value) {
      this.inputValue = this.value;
    }
  }

  handleFocusIn() {
    if (this.resultsOnInitFocus && !this.hasBeenFocusedAtLeastOnce) {
      this.performFilter('');
      this.hasBeenFocusedAtLeastOnce = true;
    }

    this.isFocused = true;
    this.isSilenced = false;
  }

  handleFocusOut() {
    this.isFocused = false;
    this.statusText = null;
    this.isSilenced = true;
  }

  private textChanged(value: string): void {
    this.originalSearch = value;
    this.performFilter(value);
    this.isSilenced = false;
    this.valueChanged.emit(value);
  }

  handleKeyPressed(event: KeyboardEvent): void {
    event.stopImmediatePropagation();

    if (event.key === Keys.UP_ARROW || event.key === Keys.DOWN_ARROW) {
      this.navigateSuggestions(event.key);
      this.updateScroll();
    } else if (event.key !== Keys.ENTER) {
      this.textChanged(this.inputValue);
      this.selectCurrentItem();
    }
  }

  handleKeyDown(event: KeyboardEvent): void {
    event.stopImmediatePropagation();

    if (event.key === Keys.TAB || event.key === Keys.ENTER) {
      this.selectCurrentItem();
    }
  }

  handleItemSelected(value: string): void {
    this.inputValue = value;
    this.textChanged(value);
    this.filterResult = new Array<string>();
    this.selectionChanged.emit(value);
  }

  private performFilter(value: string) {
    const filter = (filterList: string[], text: string) => {
      const filterResult = filterList.filter(value => {
        return text === null || text.length < 1 || value.toLowerCase().indexOf(text.toLowerCase()) > -1;
      });
      return filterResult;
    };

    this.filterResult = filter(this.filterList, value);

    this.selectedItemIndex = -1;
  }

  private addHighlight() {
    if (this.selectedItemIndex > -1) {
      const listItem = this.el.querySelector(`#${this.getListItemId(this.selectedItemIndex)}`);
      listItem.classList.add('highlighted');
    }
  }

  private removeHighlight(i: number) {
    if (i > -1) {
      const listItem = this.el.querySelector(`#${this.getListItemId(i)}`);
      listItem.classList.remove('highlighted');
    }
  }

  private selectCurrentItem(): void {
    if (this.selectedItemIndex >= 0) {
      const selectedItemText = this.filterResult[this.selectedItemIndex];
      this.handleItemSelected(selectedItemText);
    }
  }

  handleItemHovered(index: number): void {
    this.removeHighlight(this.selectedItemIndex);
    this.selectedItemIndex = index;
    this.addHighlight();
  }

  handleComponentFocusOut() {
    // Ensure dropdown closed on clicking or tabbing away from this component
    if (this.filterResult?.length > 0) {
      this.filterResult = new Array<string>();
      this.hasBeenFocusedAtLeastOnce = false;
    }
  }

  /**
   * Check if the selected option is in view, and scroll if not
   */
  private updateScroll() {
    const container = this.listContainer;

    const ul = container.querySelector('ul');
    const selectedItem: any = Array.from(ul.childNodes).find((item: any) => item.ariaPosInSet === `${this.selectedItemIndex + 1}`);

    if (container && selectedItem && container.scrollHeight + container.clientHeight) {
      selectedItem.scrollIntoView();
    }
  }

  private navigateSuggestions(key: Keys) {
    if (key === Keys.UP_ARROW) {
      this.removeHighlight(this.selectedItemIndex);
      this.selectedItemIndex--;
      if (this.selectedItemIndex === -2) {
        this.selectedItemIndex = this.filterResult.length - 1;
      }
    }
    if (key === Keys.DOWN_ARROW) {
      this.removeHighlight(this.selectedItemIndex);
      this.selectedItemIndex++;
      if (this.selectedItemIndex > this.filterResult.length - 1) {
        this.selectedItemIndex = -1;
      }
    }
    if (this.selectedItemIndex === -1) {
      this.inputValue = this.originalSearch;
    } else {
      const value = this.filterResult[this.selectedItemIndex];

      this.inputValue = value;

      this.addHighlight();
    }
  }

  private getListItemId(i: number) {
    return `${this.listId}-item-${i}`;
  }

  render() {
    return (
      <Host onFocusout={_ev => this.handleComponentFocusOut()}>
        <div class="visually-hidden">
          <div class="results-status-a" role="status" aria-atomic="true" aria-live="polite">
            {!this.isSilenced && this.isAlternateStatusSection ? this.statusText : ''}
          </div>
          <div class="results-status-b" role="status" aria-atomic="true" aria-live="polite">
            {!this.isSilenced && !this.isAlternateStatusSection ? this.statusText : ''}
          </div>
        </div>
        <admiralty-input
          type="text"
          ref={el => (this.inputControl = el)}
          label={this.label}
          placeholder={this.placeholder}
          class="filterTextInput"
          onKeyUp={ev => this.handleKeyPressed(ev)}
          onKeyDown={ev => this.handleKeyDown(ev)}
          onFocusin={_ev => this.handleFocusIn()}
          onFocusout={_ev => this.handleFocusOut()}
          aria-expanded={this.isFocused && this.filterResult.length > 0}
        ></admiralty-input>

        <span id={this.hintId} class="visually-hidden">
          When autocomplete results are available use up and down arrows to review and enter to select. Touch device users, explore by touch or with swipe gestures.
        </span>
        {this.filterResult.length > 0 ? (
          <div class="typeahead-list-container" ref={el => (this.listContainer = el)}>
            <ul class="typeahead-list" id={this.listId} role="listbox">
              {this.filterResult.map((item, i) => (
                <li
                  id={this.getListItemId(i)}
                  onMouseDown={_ev => this.handleItemSelected(item)}
                  onMouseOver={_ev => this.handleItemHovered(i)}
                  aria-selected={i === this.selectedItemIndex}
                  role="option"
                  tabindex="-1"
                  aria-posinset={i + 1}
                  aria-setsize={this.filterResult.length}
                >
                  {item}
                </li>
              ))}
            </ul>
          </div>
        ) : null}
        <slot></slot>
      </Host>
    );
  }
}

let id = 0;
