// components/expansion/expansion.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

let nextId = 0;

@Component({
  selector: 'ukho-expansion',
  templateUrl: './expansion.component.html',
  styleUrls: ['./expansion.component.scss'],
})
export class ExpansionComponent {
  @Input() initialExpanded: boolean = false;
  @Input() heading: string;
  @Input() alignHeadingRight: boolean = false;
  @Input() hideBorder: boolean = false;

  @Output() change = new EventEmitter<boolean>();

  id: string = `ukho-expansion-${++nextId}`;
  headerId: string = `${this.id}-header`;
  contentId: string = `${this.id}-content`;

  onToggle() {
    this.initialExpanded = !this.initialExpanded;
    this.change.emit(this.initialExpanded);
  }
}

<section class="expansion {{ !hideBorder ? 'bordered' : '' }} {{ initialExpanded ? 'expanded' : '' }}">
  <button
    [id]="headerId"
    type="button"
    [attr.aria-expanded]="initialExpanded"
    [attr.aria-controls]="contentId"
    (click)="onToggle()"
  >
    <h3 class="{{ alignHeadingRight ? 'expansion-heading-right-align' : '' }}">{{ heading }}</h3>
    <span class="visually-hidden">, {{ initialExpanded ? "Hide" : "Show"}} this section</span>
  </button>
  <div
    class="expansion-content"
    [id]="contentId"
    [attr.aria-labelledby]="headerId"
    [hidden]="!initialExpanded"
  >
    <ng-content></ng-content>
  </div>
</section>

// packages/core/src/components/expansion/expansion.tsx
import { Component, Event, EventEmitter, h, Prop } from '@stencil/core';

let nextId = 0;

@Component({
  tag: 'admiralty-expansion',
  styleUrl: 'expansion.scss',
  scoped: true,
})
export class ExpansionComponent {
  /**
   * The text to display in the heading of the expansion component.
   */
  @Prop() heading: string;

  /**
   * Whether the component is expanded.
   */
  @Prop({ mutable: true, reflect: true }) expanded = false;

  /**
   * CWhether the heading should be right aligned.
   */
  @Prop() alignHeadingRight = false;

  /**
   * Whether the border on the bottom of the component should be hidden.
   */
  @Prop() hideBorder = false;

  /**
   * The event that is dispatched when the expanded status is toggled.
   */
  @Event() toggled: EventEmitter<boolean>;

  internalId: string = `admiralty-expansion-${++nextId}`;

  headerId: string = `${this.internalId}-header`;
  contentId: string = `${this.internalId}-content`;

  onToggle() {
    this.expanded = !this.expanded;
    this.toggled.emit(this.expanded);
  }

  getExpansionIcon(): string {
    return this.expanded ? 'keyboard-arrow-up-rounded' : 'keyboard-arrow-down-rounded';
  }

  render() {
    return (
      <section
        class={{
          expansion: true,
          expanded: this.expanded,
          bordered: !this.hideBorder,
        }}
      >
        <button id={this.headerId} type="button" aria-expanded={this.expanded} aria-controls={this.contentId} class="expansion-heading-button" onClick={this.onToggle.bind(this)}>
          <h3 class={{ 'expansion-heading-right-align': this.alignHeadingRight }}>{this.heading}</h3>
          <span class="visually-hidden">, {this.expanded ? 'Hide' : 'Show'} this section</span>
          <admiralty-icon class="expansion-heading-icon" name={this.getExpansionIcon()}></admiralty-icon>
        </button>
        <div class="expansion-content" id={this.contentId} aria-labelledby={this.headerId} hidden={!this.expanded}>
          <slot></slot>
        </div>
      </section>
    );
  }
}
